from pathlib import Path

def r(path, old, new):
    p=Path(path); s=p.read_text()
    if old not in s: raise SystemExit(f'missing anchor {path}: {old[:90]!r}')
    p.write_text(s.replace(old,new,1))

# bridge authority: fail-closed default, explicit GUI constructor only
r('crates/bridge/src/modal_action.rs','#[derive(Default, Clone, Debug)]\npub struct ModalAction(Arc<ModalActionInner>);','#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]\npub enum AppCdsLaunchAuthority {\n    #[default]\n    Unknown,\n    NormalGui,\n}\n\n#[derive(Default, Clone, Debug)]\npub struct ModalAction(Arc<ModalActionInner>);')
r('crates/bridge/src/modal_action.rs','impl ModalAction {\n    pub fn refcnt(&self) -> usize {','impl ModalAction {\n    pub fn normal_gui_launch() -> Self {\n        let inner = ModalActionInner {\n            appcds_launch_authority: AppCdsLaunchAuthority::NormalGui,\n            ..Default::default()\n        };\n        Self(Arc::new(inner))\n    }\n\n    pub fn appcds_launch_authority(&self) -> AppCdsLaunchAuthority {\n        self.0.appcds_launch_authority\n    }\n\n    pub fn refcnt(&self) -> usize {')
r('crates/bridge/src/modal_action.rs','pub struct ModalActionInner {\n    notify: Arc<tokio::sync::Notify>,','pub struct ModalActionInner {\n    appcds_launch_authority: AppCdsLaunchAuthority,\n    notify: Arc<tokio::sync::Notify>,')
with open('crates/bridge/src/modal_action.rs','a') as f:f.write('''\n\n#[cfg(test)]\nmod appcds_launch_authority_tests {\n    use super::*;\n    #[test] fn default_and_legacy_actions_are_unknown(){let a=ModalAction::default();assert_eq!(a.appcds_launch_authority(),AppCdsLaunchAuthority::Unknown);assert_eq!(a.clone().appcds_launch_authority(),AppCdsLaunchAuthority::Unknown);}\n    #[test] fn audited_gui_start_constructor_is_normal_gui_and_clone_preserves_it(){let a=ModalAction::normal_gui_launch();assert_eq!(a.appcds_launch_authority(),AppCdsLaunchAuthority::NormalGui);assert_eq!(a.clone().appcds_launch_authority(),AppCdsLaunchAuthority::NormalGui);}\n}\n''')

r('crates/frontend/src/root.rs','''pub fn start_instance(\n    id: InstanceID,\n    name: SharedString,\n    quick_play: Option<QuickPlayLaunch>,\n    data: &DataEntities,\n    window: &mut Window,\n    cx: &mut App,\n) {\n    let modal_action = ModalAction::default();''','''pub fn start_instance(\n    id: InstanceID,\n    name: SharedString,\n    quick_play: Option<QuickPlayLaunch>,\n    data: &DataEntities,\n    window: &mut Window,\n    cx: &mut App,\n) {\n    // Sole audited GUI Start authority for AppCDS identity reuse.\n    let modal_action = ModalAction::normal_gui_launch();''')

# backend -> command transport
r('crates/backend/src/launch/mod.rs','handle::FrontendHandle, message::{MessageToFrontend, QuickPlayLaunch}, modal_action::{ModalAction, ProgressTracker, ProgressTrackerFinishType}, safe_path::SafePath','handle::FrontendHandle, message::{MessageToFrontend, QuickPlayLaunch}, modal_action::{AppCdsLaunchAuthority, ModalAction, ProgressTracker, ProgressTrackerFinishType}, safe_path::SafePath')
r('crates/backend/src/launch/mod.rs','            rule_context: launch_rule_context,\n            login_info,\n        };','            rule_context: launch_rule_context,\n            login_info,\n            appcds_launch_authority: modal_action.appcds_launch_authority(),\n        };')
r('crates/backend/src/launch/mod.rs','    pub rule_context: LaunchRuleContext,\n    pub login_info: MinecraftLoginInfo,\n}','    pub rule_context: LaunchRuleContext,\n    pub login_info: MinecraftLoginInfo,\n    pub appcds_launch_authority: AppCdsLaunchAuthority,\n}')
r('crates/backend/src/launch/mod.rs','        for arg in iter {\n            command.arg(arg.to_os_string());\n        }\n\n        #[cfg(target_os = "linux")]','        for arg in iter {\n            command.arg(arg.to_os_string());\n        }\n        command.bootoptim_appcds_launch_authority(match self.appcds_launch_authority {\n            AppCdsLaunchAuthority::Unknown => command::BootOptimAppCdsLaunchAuthority::Unknown,\n            AppCdsLaunchAuthority::NormalGui => command::BootOptimAppCdsLaunchAuthority::NormalGui,\n        });\n\n        #[cfg(target_os = "linux")]')

# command owns the control field; it never enters Java argv
r('crates/command/src/command.rs','#[derive(Debug)]\nstruct BootOptimTraining {','#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]\npub enum BootOptimAppCdsLaunchAuthority {\n    #[default]\n    Unknown,\n    NormalGui,\n}\nimpl BootOptimAppCdsLaunchAuthority { fn as_control_value(self)->&\'static str { match self { Self::Unknown=>"unknown", Self::NormalGui=>"normal-gui" } } }\n\n#[derive(Debug)]\nstruct BootOptimTraining {')
r('crates/command/src/command.rs','    pub(crate) stderr: PandoraStdioReadMode,\n    #[cfg(windows)]','    pub(crate) stderr: PandoraStdioReadMode,\n    bootoptim_appcds_launch_authority: BootOptimAppCdsLaunchAuthority,\n    #[cfg(windows)]')
r('crates/command/src/command.rs','            stderr: Default::default(),\n            #[cfg(windows)]','            stderr: Default::default(),\n            bootoptim_appcds_launch_authority: Default::default(),\n            #[cfg(windows)]')
r('crates/command/src/command.rs','    pub async fn spawn(mut self) -> std::io::Result<PandoraChild> {','    pub fn bootoptim_appcds_launch_authority(&mut self, authority: BootOptimAppCdsLaunchAuthority) { self.bootoptim_appcds_launch_authority = authority; }\n\n    pub async fn spawn(mut self) -> std::io::Result<PandoraChild> {')
r('crates/command/src/command.rs','            .arg("--upstream-commit")\n            .arg(BOOTOPTIM_PANDORA_UPSTREAM)\n            .arg("--")','            .arg("--upstream-commit")\n            .arg(BOOTOPTIM_PANDORA_UPSTREAM)\n            .arg("--appcds-launch-authority")\n            .arg(self.bootoptim_appcds_launch_authority.as_control_value())\n            .arg("--")')
with open('crates/command/src/command.rs','a') as f:f.write('''\n\n#[cfg(test)]\nmod bootoptim_appcds_authority_tests {\n use super::*;\n #[test] fn command_defaults_unknown(){let c=PandoraCommand::new("java");assert_eq!(c.bootoptim_appcds_launch_authority,BootOptimAppCdsLaunchAuthority::Unknown);}\n #[test] fn explicit_normal_gui_is_distinct(){assert_eq!(BootOptimAppCdsLaunchAuthority::Unknown.as_control_value(),"unknown");assert_eq!(BootOptimAppCdsLaunchAuthority::NormalGui.as_control_value(),"normal-gui");let mut c=PandoraCommand::new("java");c.bootoptim_appcds_launch_authority(BootOptimAppCdsLaunchAuthority::NormalGui);assert_eq!(c.bootoptim_appcds_launch_authority,BootOptimAppCdsLaunchAuthority::NormalGui);}\n}\n''')

# interposer parsing: omitted=Unknown; duplicate/malformed rejects to main STOCK
r('bootoptim-v0/interposer/src/part1.rs','    upstream_commit: String,\n    java_exe: OsString,','    upstream_commit: String,\n    identity_launch_authority: IdentityLaunchAuthority,\n    java_exe: OsString,')
r('bootoptim-v0/interposer/src/part1.rs','    finish_identity_cache_probe(probe.inventory);','    finish_identity_cache_probe(probe.inventory, parsed.identity_launch_authority);')
r('bootoptim-v0/interposer/src/part1.rs','    let mut upstream_commit = UPSTREAM_DEFAULT.to_string();\n    let mut i = 0usize;','    let mut upstream_commit = UPSTREAM_DEFAULT.to_string();\n    let mut identity_launch_authority = IdentityLaunchAuthority::Unknown;\n    let mut authority_seen = false;\n    let mut i = 0usize;')
r('bootoptim-v0/interposer/src/part1.rs','''        } else if args[i] == OsStr::new("--upstream-commit") {\n            i += 1;\n            upstream_commit = args.get(i).map(|s| s.to_string_lossy().into_owned()).unwrap_or_default();\n        } else {''','''        } else if args[i] == OsStr::new("--upstream-commit") {\n            i += 1;\n            upstream_commit = args.get(i).map(|s| s.to_string_lossy().into_owned()).unwrap_or_default();\n        } else if args[i] == OsStr::new("--appcds-launch-authority") {\n            if authority_seen { return Err(io::Error::new(io::ErrorKind::InvalidInput, "duplicate launch authority")); }\n            authority_seen = true; i += 1;\n            let value = args.get(i).ok_or_else(|| io::Error::new(io::ErrorKind::InvalidInput, "missing launch authority"))?;\n            identity_launch_authority = IdentityLaunchAuthority::from_control_arg(value.as_os_str()).ok_or_else(|| io::Error::new(io::ErrorKind::InvalidInput, "invalid launch authority"))?;\n        } else {''')
r('bootoptim-v0/interposer/src/part1.rs','    Ok(ParsedArgs { instance_dir, launcher_exe, upstream_commit, java_exe, java_args })','    Ok(ParsedArgs { instance_dir, launcher_exe, upstream_commit, identity_launch_authority, java_exe, java_args })')

r('bootoptim-v0/interposer/src/part8.rs','''#[derive(Clone, Copy, Debug, PartialEq, Eq)]\nenum IdentityLaunchAuthority { Unknown, NormalGui }\n\n// PR #19's interposer invocation has no stock-owned field that distinguishes\n// GUI Start from --run-instance/legacy callers. An environment variable is not\n// accepted as proof of launch origin. Until such authority is propagated from\n// Pandora, runtime reuse stays hard closed even when the experiment is requested.\nfn current_identity_launch_authority() -> IdentityLaunchAuthority { IdentityLaunchAuthority::Unknown }''','''#[derive(Clone, Copy, Debug, PartialEq, Eq)]\nenum IdentityLaunchAuthority { Unknown, NormalGui }\nimpl IdentityLaunchAuthority {\n    fn from_control_arg(value:&OsStr)->Option<Self>{if value==OsStr::new("unknown"){Some(Self::Unknown)}else if value==OsStr::new("normal-gui"){Some(Self::NormalGui)}else{None}}\n}''')
r('bootoptim-v0/interposer/src/part8.rs','''fn finish_identity_cache_probe(inventory: ProbeInventory) {\n    if !identity_cache_probe_requested() { return; }\n    write_identity_cache_probe(\n        identity_probe_counts(inventory),\n        current_identity_launch_authority() != IdentityLaunchAuthority::NormalGui,\n    );\n}''','''fn finish_identity_cache_probe(inventory: ProbeInventory, authority: IdentityLaunchAuthority) {\n    if !identity_cache_probe_requested() { return; }\n    write_identity_cache_probe(identity_probe_counts(inventory), authority != IdentityLaunchAuthority::NormalGui);\n}''')
r('bootoptim-v0/interposer/src/part8.rs','    #[test] fn runtime_source_is_hard_closed_until_pandora_propagates_authority(){assert_eq!(current_identity_launch_authority(),IdentityLaunchAuthority::Unknown);let c=cached();let mut e=evidence();e.authority=current_identity_launch_authority();assert_eq!(evaluate_identity_reuse(&c,&e),Err(IdentityMiss::SourceUnknown));}','    #[test] fn unknown_source_never_authorizes_reuse(){let c=cached();let mut e=evidence();e.authority=IdentityLaunchAuthority::Unknown;assert_eq!(evaluate_identity_reuse(&c,&e),Err(IdentityMiss::SourceUnknown));}\n    #[test] fn control_authority_is_explicit_and_fail_closed(){assert_eq!(IdentityLaunchAuthority::from_control_arg(OsStr::new("normal-gui")),Some(IdentityLaunchAuthority::NormalGui));assert_eq!(IdentityLaunchAuthority::from_control_arg(OsStr::new("unknown")),Some(IdentityLaunchAuthority::Unknown));assert_eq!(IdentityLaunchAuthority::from_control_arg(OsStr::new("gui")),None);let a=vec![OsString::from("--instance-dir"),OsString::from("x"),OsString::from("--"),OsString::from("java")];assert_eq!(parse_args(a).unwrap().identity_launch_authority,IdentityLaunchAuthority::Unknown);}')

# CI branch + targeted tests + packaged interposer authority gate + launcher binary markers
w=Path('.github/workflows/bootoptim-v0.yml'); s=w.read_text()
s=s.replace('      - "agent168/appcds-identity-cache-runtime-20260915"','      - "agent168/appcds-identity-cache-runtime-20260915"\n      - "agent171/appcds-gui-launch-authority-20260915"',1)
s=s.replace('      - name: Test launch probe schema and phase ordering\n        run: cargo test -p bridge launch_probe --frozen\n','      - name: Test launch probe schema and phase ordering\n        run: cargo test -p bridge launch_probe --frozen\n      - name: Test AppCDS launch authority\n        run: cargo test -p bridge appcds_launch_authority --frozen\n      - name: Test AppCDS command authority transport\n        run: cargo test -p command bootoptim_appcds_authority --frozen\n',1)
s=s.replace('      - name: Test launch probe schema and phase ordering\n        run: cargo test -p bridge launch_probe --frozen --target x86_64-pc-windows-msvc\n','      - name: Test launch probe schema and phase ordering\n        run: cargo test -p bridge launch_probe --frozen --target x86_64-pc-windows-msvc\n      - name: Test AppCDS launch authority\n        run: cargo test -p bridge appcds_launch_authority --frozen --target x86_64-pc-windows-msvc\n      - name: Test AppCDS command authority transport\n        run: cargo test -p command bootoptim_appcds_authority --frozen --target x86_64-pc-windows-msvc\n',1)
a='''      - name: Execute packaged AppCDS launch-authority contract\n        shell: pwsh\n        run: |\n          $fixture = Join-Path $env:RUNNER_TEMP "bootoptim-preflight-probe-fixture"\n          $interposer = (Resolve-Path "bootoptim-v0/interposer/target/x86_64-pc-windows-msvc/release/bootoptim-launch-interposer.exe").Path\n          $launcher = (Resolve-Path "target/x86_64-pc-windows-msvc/release/pandora_launcher.exe").Path\n          $java = Join-Path $fixture "runtime\\bin\\java.exe"\n          $classpath = Join-Path $fixture "library.jar"\n          $stockPlan = Join-Path $fixture "plan-stock.json"\n          $currentPlan = Join-Path $fixture ".bootoptim\\appcds\\launch-plan.json"\n          $env:BOOTOPTIM_APPCDS_MODE = "plan"\n          $env:BOOTOPTIM_APPCDS_IDENTITY_CACHE = "1"\n          $unknownProbe = Join-Path $fixture "identity-authority-unknown.json"\n          $env:BOOTOPTIM_APPCDS_IDENTITY_CACHE_PROBE = $unknownProbe\n          $decision = & $interposer --instance-dir $fixture --launcher-exe $launcher --upstream-commit 4eb6c7849561151695288443c106519774ee05ea --appcds-launch-authority unknown -- $java -cp $classpath com.moulberry.pandora.LaunchWrapper\n          if ($LASTEXITCODE -ne 0 -or ($decision | Out-String).Trim() -ne "STOCK") { throw "unknown authority contract failed" }\n          $unknown = Get-Content $unknownProbe -Raw | ConvertFrom-Json\n          if ($unknown.runtime_reuse_authorized -ne $false) { throw "unknown authority authorized reuse" }\n          if (Compare-Object ([System.IO.File]::ReadAllBytes($stockPlan)) ([System.IO.File]::ReadAllBytes($currentPlan)) -SyncWindow 0) { throw "unknown authority changed plan bytes" }\n          $guiProbe = Join-Path $fixture "identity-authority-normal-gui.json"\n          $env:BOOTOPTIM_APPCDS_IDENTITY_CACHE_PROBE = $guiProbe\n          $decision = & $interposer --instance-dir $fixture --launcher-exe $launcher --upstream-commit 4eb6c7849561151695288443c106519774ee05ea --appcds-launch-authority normal-gui -- $java -cp $classpath com.moulberry.pandora.LaunchWrapper\n          if ($LASTEXITCODE -ne 0 -or ($decision | Out-String).Trim() -ne "STOCK") { throw "normal-gui authority contract failed" }\n          $gui = Get-Content $guiProbe -Raw | ConvertFrom-Json\n          if ($gui.runtime_reuse_authorized -ne $true) { throw "normal-gui authority was not preserved" }\n          if (Compare-Object ([System.IO.File]::ReadAllBytes($stockPlan)) ([System.IO.File]::ReadAllBytes($currentPlan)) -SyncWindow 0) { throw "normal-gui authority changed plan bytes" }\n          Copy-Item $guiProbe "bootoptim-v0/identity-authority-selftest.json"\n          Remove-Item Env:BOOTOPTIM_APPCDS_IDENTITY_CACHE -ErrorAction SilentlyContinue\n          Remove-Item Env:BOOTOPTIM_APPCDS_IDENTITY_CACHE_PROBE -ErrorAction SilentlyContinue\n          Remove-Item Env:BOOTOPTIM_APPCDS_MODE -ErrorAction SilentlyContinue\n\n'''
if '      - name: Verify packaged binary linkage\n' not in s: raise SystemExit('workflow authority step anchor missing')
s=s.replace('      - name: Verify packaged binary linkage\n',a+'      - name: Verify packaged binary linkage\n',1)
s=s.replace('foreach ($marker in @("bootoptim.launch_probe.v1", "launcher_pre_java", "java_spawn"))','foreach ($marker in @("bootoptim.launch_probe.v1", "launcher_pre_java", "java_spawn", "--appcds-launch-authority", "normal-gui"))',1)
s=s.replace('          Copy-Item bootoptim-v0/identity-cache-probe-selftest.json bootoptim-v0/dist/APPCDS_IDENTITY_CACHE_PROBE_SELFTEST.json','          Copy-Item bootoptim-v0/identity-cache-probe-selftest.json bootoptim-v0/dist/APPCDS_IDENTITY_CACHE_PROBE_SELFTEST.json\n          Copy-Item bootoptim-v0/identity-authority-selftest.json bootoptim-v0/dist/APPCDS_LAUNCH_AUTHORITY_SELFTEST.json',1)
w.write_text(s)
