use std::{error::Error, path::Path};

use indexmap::IndexMap;

fn main() {
    println!("cargo:rerun-if-changed=./locales.toml");
    println!("cargo:rerun-if-changed=build.rs");

    let dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let dir = Path::new(&dir);

    if let Err(err) = inner(dir) {
        let lib = dir.join("src").join("lib.rs");
        let err = format!("{}", err);
        let mut contents = format!("compile_error!({err:?});\n\n");
        for line in err.lines() {
            contents.push_str("// ");
            contents.push_str(line);
            contents.push_str("\n");
        }
        std::fs::write(&lib, contents.as_bytes()).unwrap();
    }
}

fn inner(dir: &Path) -> Result<(), Box<dyn Error>> {
    let mut content = String::new();

    content.push_str("// DO NOT EDIT THIS FILE. THIS FILE IS AUTOGENERATED BY crates/t/build.rs\n");

    let data = std::fs::read(dir.join("locales.toml"))?;
    let data = toml::from_slice::<toml::Value>(&data)?;

    let locales = Locales::new(data)?;

    content.push_str(r#"
static LANG: std::sync::atomic::AtomicU8 = std::sync::atomic::AtomicU8::new(0);

#[derive(Clone, Debug, PartialEq, Default, serde::Serialize, serde::Deserialize)]
#[serde(from = "String", into = "String")]
pub enum Language {
	#[default]
	System,
	Code(String),
}

impl From<String> for Language {
	fn from(s: String) -> Self {
		match s.as_str() {
			"system" => Language::System,
			_ => Language::Code(s),
		}
	}
}

impl From<Language> for String {
	fn from(lang: Language) -> Self {
		match lang {
			Language::System => String::from("system"),
			Language::Code(code) => code,
		}
	}
}

fn language_to_id(lang: &Language) -> u8 {
    match lang {
        Language::System => {
            for locale in sys_locale::get_locales() {
                let lower = locale.to_ascii_lowercase().replace('-', "_");
                if let Some(id) = lang_code_to_id(&lower) {
                    return id;
                }
                if let Some((first, _)) = lower.split_once('_') {
                    if let Some(id) = lang_code_to_id(first) {
                        return id;
                    }
                }
            }
            0
        },
        Language::Code(code) => {
            lang_code_to_id(&code).unwrap_or(0)
        },
    }
}

pub fn get_current_lang_id() -> u8 {
    LANG.load(std::sync::atomic::Ordering::Relaxed)
}

pub fn set_lang(lang: &Language) {
    LANG.store(language_to_id(lang), std::sync::atomic::Ordering::Relaxed);
}

"#);

    // lang_code_to_id function
    content.push_str("fn lang_code_to_id(code: &str) -> Option<u8> {\n");
    content.push_str("\tmatch code {\n");

    for (lang_str, lang_id) in &locales.languages {
        content.push_str("\t\t\"");
        content.push_str(&lang_str);
        content.push_str("\" => Some(");
        content.push_str(&format!("{}", lang_id));
        content.push_str("),\n");
    }
    content.push_str("\t\t_ => None,\n");
    content.push_str("\t}\n");
    content.push_str("}\n\n");

    // languages function
    content.push_str("pub fn languages() -> &'static [(&'static str, &'static str)] {\n");
    content.push_str("\t&[\n");
    for (code, name) in &locales.language_names {
        content.push_str(&format!("\t\t({:?}, {:?}),\n", code, name));
    }
    content.push_str("\t]\n");
    content.push_str("}\n\n");

    // locale data
    for root in &locales.roots {
        locales.nodes[*root].write(&locales, 0, &mut content);
    }

    let generated = Path::new(&std::env::var("OUT_DIR").unwrap()).join("generated.rs");
    std::fs::write(&generated, content.as_bytes())?;
    Ok(())
}

#[derive(Debug)]
struct LocaleNode {
    name: String,
    val: LocaleNodeVal,
}

static INDENTATION: &'static str = "                                    ";

impl LocaleNode {
    pub fn write(&self, locales: &Locales, indentation: usize, content: &mut String) {
        match &self.val {
            LocaleNodeVal::Parent { children, static_translation_children } => {
                content.push_str(&INDENTATION[..indentation*4]);
                content.push_str("#[rustfmt::skip]\n");
                content.push_str(&INDENTATION[..indentation*4]);
                content.push_str("pub mod ");
                content.push_str(&self.name);
                content.push_str(" {\n");

                if !static_translation_children.is_empty() {
                    let has_short = static_translation_children.iter().any(|(_, index)| {
                        let LocaleNodeVal::Leaf { short_translations, .. } = &locales.nodes[*index].val else {
                            unreachable!();
                        };
                        !short_translations.is_empty()
                    });

                    content.push_str(&INDENTATION[..indentation*4+4]);
                    if has_short {
                        content.push_str("pub fn get(key: &str, short: bool) -> Option<&'static str> {\n");
                    } else {
                        content.push_str("pub fn get(key: &str) -> Option<&'static str> {\n");
                    }
                    content.push_str(&INDENTATION[..indentation*4+8]);
                    content.push_str("match key {\n");
                    for (key, index) in static_translation_children {
                        content.push_str(&INDENTATION[..indentation*4+12]);
                        content.push_str(&format!("{:?}", key));
                        content.push_str(" => Some(");
                        content.push_str(&locales.nodes[*index].name);
                        let LocaleNodeVal::Leaf { short_translations, .. } = &locales.nodes[*index].val else {
                            unreachable!();
                        };
                        if short_translations.is_empty() {
                            content.push_str("()),\n");
                        } else {
                            content.push_str("(short)),\n");
                        }
                    }
                    content.push_str(&INDENTATION[..indentation*4+12]);
                    content.push_str("_ => None,\n");
                    content.push_str(&INDENTATION[..indentation*4+8]);
                    content.push_str("}\n");
                    content.push_str(&INDENTATION[..indentation*4+4]);
                    content.push_str("}\n");
                }

                for child in children {
                    locales.nodes[*child].write(&locales, indentation+1, content);
                }

                content.push_str(&INDENTATION[..indentation*4]);
                content.push_str("}\n");
            },
            LocaleNodeVal::Leaf { arguments, translations, short_translations } => {
                content.push_str(&INDENTATION[..indentation*4]);
                content.push_str("pub fn ");
                content.push_str(&self.name);
                if arguments.is_empty() {
                    if short_translations.is_empty() {
                        content.push_str("() -> &'static str {\n");
                    } else {
                        content.push_str("(short: bool) -> &'static str {\n");
                    }
                } else {
                    content.push_str("(");
                    let mut first = true;
                    for (param, ty) in arguments {
                        if first {
                            first = false;
                        } else {
                            content.push_str(", ");
                        }
                        content.push_str(param);
                        content.push_str(": ");
                        content.push_str(ty);
                    }
                    if !short_translations.is_empty() {
                        content.push_str(", short: bool");
                    }
                    content.push_str(") -> String {\n");
                }
                content.push_str(&INDENTATION[..indentation*4+4]);
                content.push_str("match crate::LANG.load(std::sync::atomic::Ordering::Relaxed) {\n");
                let mut end = String::new();
                for (key, value) in translations {
                    let target = if *key == 0 {
                        &mut end
                    } else {
                        &mut *content
                    };

                    target.push_str(&INDENTATION[..indentation*4+8]);
                    if *key == 0 {
                        target.push('_');
                    } else {
                        target.push_str(&format!("{}", key));
                    }
                    target.push_str(" => ");

                    let has_short;
                    if let Some(short) = short_translations.get(key) {
                        target.push_str("if short { ");

                        if !arguments.is_empty() {
                            target.push_str("format!(");
                        }
                        target.push_str(&format!("{short:?}"));
                        if !arguments.is_empty() {
                            target.push_str(")");
                        }

                        target.push_str(" } else { ");
                        has_short = true;
                    } else {
                        has_short = false;
                    }

                    if !arguments.is_empty() {
                        target.push_str("format!(");
                    }
                    target.push_str(&format!("{value:?}"));
                    if !arguments.is_empty() {
                        target.push_str(")");
                    }

                    if has_short {
                        target.push_str(" }");
                    }

                    target.push_str(",\n");
                }
                if !end.is_empty() {
                    content.push_str(&end);
                }
                content.push_str(&INDENTATION[..indentation*4+4]);
                content.push_str("}\n");
                content.push_str(&INDENTATION[..indentation*4]);
                content.push_str("}\n");

            },
        }
    }
}

#[derive(Debug)]
enum LocaleNodeVal {
    Parent {
        children: Vec<usize>,
        static_translation_children: Vec<(String, usize)>,
    },
    Leaf {
        arguments: Vec<(String, String)>,
        translations: IndexMap<u8, String>,
        short_translations: IndexMap<u8, String>,
    },
}

#[derive(Default, Debug)]
struct Locales {
    roots: Vec<usize>,
    nodes: Vec<LocaleNode>,
    languages: IndexMap<String, u8>,
    language_names: IndexMap<String, String>,
}

impl Locales {
    fn new(data: toml::Value) -> Result<Self, Box<dyn Error>> {
        let mut locales = Self::default();

        let toml::Value::Table(mut root) = data else {
            return Err(format!("Root is not a table: {data:?}").into());
        };

        locales.languages.insert("en".to_string(), 0);

        if let Some(toml::Value::Table(mut language)) = root.remove("language") {
            if let Some(toml::Value::Table(names)) = language.remove("name") {
                for (code, value) in names {
                    if let toml::Value::String(name) = value {
                        locales.language_names.insert(code, name);
                    }
                }
            }
        }

        for (key, value) in root {
            let vals = locales.create(value)?;

            for val in vals {
                locales.roots.push(locales.nodes.len());
                locales.nodes.push(LocaleNode {
                    name: key.clone(),
                    val
                });
            }
        }

        Ok(locales)
    }

    fn create(&mut self, data: toml::Value) -> Result<Vec<LocaleNodeVal>, Box<dyn Error>>  {
        match data {
            toml::Value::Table(map) => {
                let mut has_string = false;
                let mut has_table = false;
                for (_, value) in &map {
                    has_string |= matches!(value, toml::Value::String(_));
                    has_table |= matches!(value, toml::Value::Table(_));
                }

                let mut vals = Vec::new();

                if has_string {
                    let mut arguments: Vec<(String, String)> = Vec::new();
                    let mut translations = IndexMap::default();
                    let mut short_translations = IndexMap::default();
                    for (key, value) in &map {
                        let mut value = match value {
                            toml::Value::String(string) => string.clone(),
                            _ => continue,
                        };

                        let (key, short) = if key.ends_with("_short") {
                            (&key[..key.len()-"_short".len()], true)
                        } else {
                            (key.as_str(), false)
                        };

                        let next_language_id = self.languages.len() as u8;
                        let language_id = *self.languages.entry(key.to_string()).or_insert(next_language_id);

                        if value.contains("${") {
                            let mut from = 0;
                            while let Some(index) = value[from..].find('$') {
                                let index = index + from;

                                let Some(next) = value.as_bytes().get(index+1) else {
                                    break;
                                };
                                if *next == b'{' {
                                    let Some(end) = value[index+1..].find('}') else {
                                        break;
                                    };

                                    let inner = &value[index+2..index+1+end];

                                    let Some((name, ty)) = inner.split_once(':') else {
                                        return Err("Format argument must be `param: type`".into());
                                    };
                                    let name = name.trim_ascii();
                                    let ty = ty.trim_ascii();

                                    let mut has_existing = false;
                                    for existing in &arguments {
                                        if existing.0 == name {
                                            if existing.1 != ty {
                                                return Err(format!("Multiple arguments with different types: {} in {}", existing.0, value).into());
                                            }
                                            has_existing = true;
                                        }
                                    }

                                    if !has_existing {
                                        arguments.push((name.to_string(), ty.to_string()));
                                    }

                                    value.replace_range(index..index+2+end, &format!("{{{name}}}"));

                                    from = index+2;
                                } else {
                                    from = index+1;
                                }
                            }
                        }

                        if short {
                            short_translations.insert(language_id, value);
                        } else {
                            translations.insert(language_id, value);
                        }
                    }
                    vals.push(LocaleNodeVal::Leaf {
                        arguments,
                        translations,
                        short_translations,
                    });
                }
                if has_table {
                    let mut children = Vec::new();
                    let mut static_translation_children = Vec::new();
                    for (key, value) in map {
                        let toml::Value::Table(_) = &value else {
                            continue;
                        };

                        let vals = self.create(value)?;

                        let original_name = key.clone();
                        let name = if key == "mod" {
                            "mod_".to_string()
                        } else if !key.starts_with(|c| char::is_alphabetic(c)) {
                            format!("_{key}")
                        } else {
                            key
                        };
                        let name = name.replace("+", "_plus");
                        let name = name.replace("-", "_minus");

                        for val in vals {
                            if let LocaleNodeVal::Leaf { arguments, .. } = &val {
                                if arguments.is_empty() {
                                    static_translation_children.push((original_name.clone(), self.nodes.len()));
                                }
                            }

                            children.push(self.nodes.len());
                            self.nodes.push(LocaleNode {
                                name: name.clone(),
                                val
                            });
                        }
                    }
                    vals.push(LocaleNodeVal::Parent {
                        children,
                        static_translation_children
                    });
                }
                return Ok(vals);
            },
            _ => {
                return Err(format!("Unexpected value: {data:?}").into())
            },
        }
    }
}
